export const FETCH_CHATS = 'FETCH_CHATS';
export const FETCH_USERS = 'FETCH_USERS';
export const NEW_CHAT = 'NEW_CHAT';


export const NEW_MESSAGE_NOTIFICATION = 'NEW_MESSAGE_NOTIFICATION';
export const USER_JOIN_CHAT_NOTIFICATION = 'USER_JOIN_CHAT_NOTIFICATION';
export const USER_LEAVE_CHAT_NOTIFICATION = 'USER_LEAVE_CHAT_NOTIFICATION';
export const NEW_HISTORY_NOTIFICATION = 'NEW_HISTORY_NOTIFICATION';


export const SEND_MESSAGE = 'SEND_MESSAGE';
export const JOIN_CHAT = 'JOIN_CHAT';



